apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;
      
      location / {
        proxy_pass http://movie-service:8000; 
      }
      
      location /api/v1/casts/ {
        proxy_pass http://cast-service:8000;  
      }
    }
