apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;
      
      location / {
        proxy_pass http://movie-service:8000;
      }
    }
