apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;

      location /movies/ {
        proxy_pass http://movie-service:8000;
      }

      location /casts/ {
        proxy_pass http://cast-service:8000;
      }
    }