apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: {{ .Values.image.movieService.repository }}:{{ .Values.image.movieService.tag }}
        env:
          - name: DATABASE_URI
            value: {{ .Values.env.movieService.DATABASE_URI }}
          - name: CAST_SERVICE_HOST_URL
            value: {{ .Values.env.movieService.CAST_SERVICE_HOST_URL }}
        ports:
          - containerPort: 8000

