apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
      - name: cast-service
        image: {{ .Values.image.castService.repository }}:{{ .Values.image.castService.tag }}
        env:
          - name: DATABASE_URI
            value: {{ .Values.env.castService.DATABASE_URI }}
        ports:
          - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /api/v1/casts/docs
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/casts/docs
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10