apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.movieService.port }}
      targetPort: {{ .Values.service.movieService.targetPort }}
  type: ClusterIP
