apiVersion: v1
kind: Service
metadata:
  name: cast-service
spec:
  selector:
    app: cast-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.castService.port }}
      targetPort: {{ .Values.service.castService.targetPort }}
  type: ClusterIP
