apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: {{ .Values.service.nginx.port }}
      targetPort: {{ .Values.service.nginx.targetPort }}
      nodePort: {{ .Values.service.nginx.nodePort }}
  type: NodePort