apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
  labels:
    app: cast-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
      - name: cast-service
        image: bastienfaucher/cast_service:v.42.0
        env:
          - name: DATABASE_URI
            value: "postgresql://cast_db_username:cast_db_password@cast-db.cast-db:5432/cast_db_dev"
        ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: cast-service
spec:
  selector:
    app: cast-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
