apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
  labels:
    app: movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: bastienfaucher/movie-service-test:latest
        env:
          - name: DATABASE_URI
            value: "postgresql://movie_db_username:movie_db_password@movie-db.movie-db:5432/movie_db_dev"
          - name: CAST_SERVICE_HOST_URL
            value: "http://cast-service:8000/api/v1/casts/"
        ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
